baseurl     : "http://abhijit.mamarde.com"
title       : "Abhijit's Blog"
MetaDataFormat: yaml
params:
  author: "Abhijit"
  description: "Write to express, feel, learn..."
  disqusShortname : "mamarde"
